ASPCoreMVCAssignment02/Controllers/DepartmentController.cs
using BLL.internalinterface;
using BLL.Reposities;
using DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Assignment02.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        //private readonly IDepartmentRepository _departmentRepository;

        public DepartmentController(/*IDepartmentRepository departmentRepository*/ IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            //_departmentRepository = departmentRepository;
        }
        public async Task <IActionResult> Index()
        {
            //ViewData["Message"] = "Hello From Department Controller! [ViewData]";
            //ViewBag.MessageViewBag = "Hello From Department Controller! [ViewBag]";
            TempData.Keep("Message");
            var departemt = await _unitOfWork.DepartmentRepository.GetALL();
            return View(departemt);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task <IActionResult> Create(Department department)
        {
            if (ModelState.IsValid)
            {
                await _unitOfWork.DepartmentRepository.Add(department);
                TempData["Message"] = "Hello From Department Controller (Create => Index) [TempData]";
                return RedirectToAction("Index");

            }
            return View(department);
        }
        public async Task <IActionResult> Details( int? id)
        {
            if( id is null)
                return  NotFound();
            var department = await _unitOfWork.DepartmentRepository.Get(id.Value);

            if (department is null)
                return NotFound();

            return View(department);

        }
        
        public async Task <IActionResult> Update(int? id)
        {
            if (id is null)
                return NotFound();
            var department = await _unitOfWork.DepartmentRepository.Get(id.Value);

            if (department is null)
                return NotFound();

            return View(department);

        }
        [HttpPost]
        public async Task <IActionResult> Update(int? id,Department department)
        {
            if (id != department.Id)
                return NotFound();
            if (ModelState.IsValid)
            {
                
                try
                {
                    await _unitOfWork.DepartmentRepository.Update(department);
                    return RedirectToAction("Index");

                }
                catch (Exception ex )
                {
                    return View(department);

                }
            }
            return View(department);
        }

        public async Task<IActionResult> Delele(int? id)
        {
            if (id is null)
                return NotFound();

            var department = await _unitOfWork.DepartmentRepository.Get(id);

            if (department is null)
                return NotFound();

            await _unitOfWork.DepartmentRepository.Delete(department);
            return RedirectToAction("Index");

            //return View(employee);
        }




        //[HttpPost]
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }


        //    var department = await _departmentRepository.Get(id);

        //    if (department == null)
        //    {
        //        return NotFound();

        //    }
        //    await _departmentRepository.Delete(department);
        //    return RedirectToAction("Index");

        //}




    }
}

ASPCoreMVCAssignment02/Controllers/EmployeeController.cs
using Assignment02.Helper;
using Assignment02.Models;
using AutoMapper;
using BLL.internalinterface;
using BLL.Reposities;
using DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Assignment02.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        //private readonly IEmployeeRepository _employeeRepository ;
        //private readonly IDepartmentRepository _departmentRepository;

        public EmployeeController(/*IEmployeeRepository employeeRepository */
            //, IDepartmentRepository departmentRepository,
            IUnitOfWork unitOfWork,
            IMapper mapper)
        {
            //_employeeRepository = employeeRepository ;
            //_departmentRepository = departmentRepository;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(string SearchValue = "")
        {
            IEnumerable<Employee> employees;
            if (string.IsNullOrEmpty(SearchValue))
            {
                employees = await _unitOfWork.EmployeeRepository.GetALL();

            }
            else
            {
                employees = await _unitOfWork.EmployeeRepository.Search(SearchValue);
            }

            var mappedEmployees = _mapper.Map<IEnumerable<EmployeeViewModel>>(employees);
            return View(mappedEmployees);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Departments = await _unitOfWork.DepartmentRepository.GetALL();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel employeeViewModel)
        {
            if (ModelState.IsValid)
            {

                employeeViewModel.ImageUrl = DocumentSettings.UploadFile(employeeViewModel.Image, "Files/Imgs");
                var mappedEmployee = _mapper.Map<Employee>(employeeViewModel);

                await _unitOfWork.EmployeeRepository.Add(mappedEmployee );
                return RedirectToAction("Index");

            }
            return View(employeeViewModel);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
                return NotFound();
            var employee = await _unitOfWork.EmployeeRepository.Get(id.Value);

            var mappedEmployee = _mapper.Map<EmployeeViewModel>(employee);

            var departmentName  = await _unitOfWork.EmployeeRepository.GetDepartmentByEmployeeId(id);

            employee.Department.Name = departmentName;

            if (employee is null)
                return NotFound();

            return View(mappedEmployee);

        }
        public async Task<IActionResult> Update(int? id)
        {
            if (id is null)
                return NotFound();
            var employee = await _unitOfWork.EmployeeRepository.Get(id.Value);


            var mappedEmployee = _mapper.Map<EmployeeViewModel>(employee);


            if (employee is null)
                return NotFound();

            return View(mappedEmployee);

        }
        [HttpPost]
        public async Task<IActionResult> Update(int? id, EmployeeViewModel employeeViewModel)
        {
            if (id != employeeViewModel.Id)
                return NotFound();
            if (ModelState.IsValid)
            {

                try
                {
                    employeeViewModel.ImageUrl = DocumentSettings.UploadFile(employeeViewModel.Image, "Files/Imgs");

                    var mappedEmployee = _mapper.Map<Employee>(employeeViewModel);
                    await _unitOfWork.EmployeeRepository.Update(mappedEmployee);
                    return RedirectToAction("Index");

                }
                catch (Exception ex)
                {
                    return View(employeeViewModel);

                }
            }
            return View(employeeViewModel);
        }
        
        public async Task<IActionResult> Delele(int? id)
        {
            if (id is null)
                return NotFound();

            var employee = await _unitOfWork.EmployeeRepository.Get(id);

            if (employee is null)
                return NotFound();

            DocumentSettings.DeleteFile("Imgs", employee.ImageUrl);

            await _unitOfWork.EmployeeRepository.Delete(employee);
            return RedirectToAction("Index");

            //return View(employee);
        }
    }
}

ASPCoreMVCAssignment02/Controllers/RolesController.cs
using AutoMapper;
using DAL.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment02.Controllers
{
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole identityRole)
        {
            if (ModelState.IsValid) 
            {
                var result = await _roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                    return RedirectToAction("Index");

                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);
                return View(identityRole);
            }
            return View(identityRole);
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id is null)
                return NotFound();

            var role = await _roleManager.FindByIdAsync(id);


            if (role is null)
                return NotFound();


            return View(role);
        }
        public async Task<IActionResult> Update(string id)
        {

            if (id is null)
                return NotFound();

            var role = await _roleManager.FindByIdAsync(id);


            if (role is null)
                return NotFound();

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id, IdentityRole identityRole)
        {
            if (id != identityRole.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);

                    role.Name = identityRole.Name;
                    role.NormalizedName = identityRole.Name.ToUpper();

                    var result = await _roleManager.UpdateAsync(role);

                    if (result.Succeeded)
                        return RedirectToAction("Index");

                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);



                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(identityRole);

        }
        public async Task<IActionResult> Delete(string id)
        {
            if (id is null)
                return NotFound();
            try
            {
                var role = await _roleManager.FindByIdAsync(id);

                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");

                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);

            }
            catch (Exception ex)
            {
                throw;
            }
            return RedirectToAction("Index");
        }
    }
}

ASPCoreMVCAssignment02/Controllers/UsersController.cs
using AutoMapper;
using DAL.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment02.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UsersController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string SearchValue = "")
        {

            if (string.IsNullOrEmpty(SearchValue))
            {
                var users = _userManager.Users.ToList();
                return View(users);
            }

            else
            {
                var user = await _userManager.FindByNameAsync(SearchValue);
                return View(new List<ApplicationUser> { user });
            }


        }
        public async Task<IActionResult> Details(string id)
        {
            if (id is null)
                return NotFound();

            var user = await _userManager.FindByIdAsync(id);


            if (user is null)
                return NotFound();

            return View(user);
        }
        public async Task<IActionResult> Update(string id)
        {

            if (id is null)
                return NotFound();

            var user = await _userManager.FindByIdAsync(id);


            if (user is null)
                return NotFound();

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id, ApplicationUser applicationUser)
        {
            if (id != applicationUser.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.FindByIdAsync(id);

                    user.UserName = applicationUser.UserName;
                    user.NormalizedUserName = applicationUser.UserName.ToUpper();
                    user.PhoneNumber = applicationUser.PhoneNumber;

                    var result = await _userManager.UpdateAsync(user);

                    if (result.Succeeded)
                        return RedirectToAction("Index");

                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);



                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View();

        }
        
        public async Task<IActionResult> Delete(string id)
        {
            if (id is null)
                return NotFound();
            try
            {
                var user = await _userManager.FindByIdAsync(id);

                var result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Index");

                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);

            }
            catch (Exception ex)
            {
                throw;
            }
            return RedirectToAction("Index");
        }
    }
        
}

ASPCoreMVCAssignment02/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title> SignUp Page</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/authLayout.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1> @ViewData["Title"] </h1>
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->


	<script src="~/lib/jquery/dist/jquery.min.js"></script>

	@await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>

ASPCoreMVCAssignment02/Views/Shared/_ButtonsViewPartial.cshtml
@model string

<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-success"> Details </a>
</td>
<td>
    <a asp-action="Update" asp-route-id="@Model" class="btn btn-warning"> Update </a>
</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger"> Delete  </a>
</td>

ASPCoreMVCAssignment02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPCoreMVCAssignment02</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment02</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn-danger" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Assignment02 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>